FROM alpine/git
WORKDIR /
RUN git clone https://github.com/Genez-io/genezio.git


FROM node:20.15.0-alpine3.20
RUN apk add --no-cache unzip
RUN apk add --no-cache git
COPY --from=0 /genezio /genezio
WORKDIR /genezio
RUN npm i
RUN npm run install-locally-dev

WORKDIR /app
COPY . .
ENV GENEZIO_API_BASE_URL=https://dev.api.genez.io
RUN npm install
