apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: genezio-build-git-template-dev
spec:
  serviceAccountName: argo-workflow
  entrypoint: build-git-dev
  imagePullSecrets:
  - name: regcred
  templates:
  - name: build-git-dev
    inputs:
      parameters:
      - name: token
      - name: githubRepository
      - name: region
      - name: projectName
      - name: basePath
    container:
      requests:
        cpu: 1500m
        memory: 1500Mi
      limit:
        cpu: 2000m
        memory: 2000Mi
      image: 408878048420.dkr.ecr.us-east-1.amazonaws.com/genezio-build-git-dev:latest
      command: [node]
      args: ["/app/index.js", "{{inputs.parameters.token}}", "{{inputs.parameters.githubRepository}}", "{{inputs.parameters.projectName}}", "{{inputs.parameters.region}}", "{{inputs.parameters.basePath}}"]
