apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: genezio-build-s3-template-dev
spec:
  serviceAccountName: argo-workflow
  entrypoint: build-s3-dev
  imagePullSecrets:
  - name: regcred
  templates:
  - name: build-s3-dev
    inputs:
      artifacts:
      - name: codeArchive
        path: /tmp/projectCode.zip
      parameters:
      - name: token
      - name: stage
    container:
      requests:
        cpu: 1500m
        memory: 1500Mi
      limit:
        cpu: 2000m
        memory: 2000Mi
      image: harbor-registry.prod.cluster.genez.io/genezio/genezio-build-dev:latest
      command: [node]
      args: ["/app/dist/index.js", "s3", "{{inputs.parameters.token}}", "{{inputs.parameters.stage}}"]
