apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: genezio-build-s3-template
spec:
  serviceAccountName: argo-workflow
  entrypoint: build-s3
  imagePullSecrets:
  - name: regcred
  templates:
  - name: build-s3
    inputs:
      artifacts:
      - name: codeArchive
        path: /tmp/projectCode.zip
      parameters:
      - name: token
      - name: stage
    container:
      requests:
        cpu: 1500m
        memory: 1500Mi
      limit:
        cpu: 2000m
        memory: 2000Mi
      image: 408878048420.dkr.ecr.us-east-1.amazonaws.com/genezio-build-prod:latest
      command: [node]
      args: ["/app/dist/index.js", "s3", "{{inputs.parameters.token}}", "{{inputs.parameters.stage}}"]
