apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: genezio-build-s3-template
spec:
  serviceAccountName: argo-workflow
  entrypoint: build-s3
  templates:
  - name: build-s3
    inputs:
      artifacts:
      - name: codeArchive
        path: /tmp/projectCode.zip
      parameters:
      - name: token
      - name: codeURL
    container:
      image: harbor-registry.prod.cluster.genez.io/genezio/genezio-build-s3
      command: [node]
      args: ["/app/index.js", "{{inputs.parameters.token}}"]
