FROM node:20.15.0-alpine3.20
RUN apk add --no-cache git
RUN apk add --no-cache unzip
RUN git clone --branch dev https://github.com/Genez-io/genezio.git

WORKDIR /genezio
RUN npm i
RUN npm run install-locally-dev

WORKDIR /app
COPY . .
RUN npm install -v 
