FROM node:20.15.0-alpine3.20

# Dependencies
# Hugo framework
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing dart-sass
RUN apk add --no-cache go
RUN apk add --no-cache git
# Python
RUN apk add --no-cache python3 && ln -sf python3 /usr/bin/python

# Other utilities
RUN apk add --no-cache unzip

# Genezio dev version
RUN git clone --branch dev https://github.com/Genez-io/genezio.git
WORKDIR /genezio
RUN npm i
RUN npm run install-locally-dev

# Build program
WORKDIR /app
COPY . .
ENV GENEZIO_API_BASE_URL=https://dev.api.genez.io
RUN npm install 
RUN npm run build
