FROM imbios/bun-node:22-alpine-git

# Dependencies
# Hugo framework
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main icu-libs
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing dart-sass
RUN apk add --no-cache go
RUN apk add --no-cache git
# Python
RUN apk add --no-cache python3 && ln -sf python3 /usr/bin/python

# Other utilities
RUN apk add --no-cache unzip

# Genezio dev version
RUN git clone --branch dev https://github.com/Genez-io/genezio.git /genezio

WORKDIR /genezio
RUN npm i
RUN npm run install-locally-dev

# Build program
ENV GENEZIO_API_BASE_URL=https://dev.api.genez.io
ENV GENEZIO_API_BUILD_URL=https://build-system-dev.genez.io

WORKDIR /app
COPY . .
RUN npm install 
RUN npm run build
