name: Deployment for Build System API dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !failure() && !cancelled() }}
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.1.0
    - name: Run script file
      working-directory: .
      run: chmod +x ./deploy.sh && ./deploy.sh dev
      shell: bash
